apps:
  - script: bin/start-server-worker.js
    name: 'portal-api'
    instances: 1
    exec_mode: fork
    cwd: '/netop-worker/files'
    env:
      PORT: 8083
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NODE_CONFIG_DIR: '/netop-worker/config/env'
      RABBITMQ_URI: 'netopusr:netoppwd@<rabbitmqhost>:<rabbitmqport>/<rabbitmqvhost>'
      RABBITMQ_HEARTBEAT: 30
      RABBITMQ_EXCHANGE_NAME: 'netop-local-netopExchange'
      RABBITMQ_EXCHANGE_TYPE: 'topic'
      NODE_ENV: 'production'
      SMTP_USER: 'AKIAJFBOXRCALLKPVICA'
      SMTP_PASS: 'AsFlrbFIBNeFiwdmjIpdCBTpI/dlLzsxpyHxe27xfLRj'
      SMTP_SENDER: 'devteam_portal@netop.com'
      REDIS_HOST: '<redishost>'
      REDIS_PORT: 6379
      NODE_DEVICE_ROLEASSIGNMENT: 'a46e37632fa6ca51a13fe39a1457946710814651'
      NODE_ENROLL_DEVICE: 'd26eae87829adde551bf4b85145794671081'
      DEVICE_ROLE_ASSIGNMENT_NAME: 'Administrator'
      ENROLL_DEVICE_NAME: 'Add device'
      RABBITMQ_MESSAGE_TIMEOUT: 5
      RABBITMQ_CHECK_TIMER: 500
      PORTALDELTAADMINAPIKEY: '4fce711a160868ed7b8d2a191fe1fb3d'
      DB_URI: 'mysql://root:dev@<host>/portal'
      SUPERADMIN_ACCOUNT: '063947fdeb68fb5843238f24adbe94ae48200dc7'
      SYSTEM_USER_ID: 'SYSTEM_USER_ID'
      NODEJS_FILETOSTART: 'bin/start-server-worker.js'
      NETOP_WORKER_ID: '<DOCKER_HOST_NAME>'
    out_file: '/netop-worker/logs/<DOCKER_HOST_NAME>-output-pm2.log'
    error_file: '/netop-worker/logs/<DOCKER_HOST_NAME>-error-pm2.log'
    log_date_format : 'YYYY-MM-DD HH:mm Z'
    merge_logs: true
